### ISSUE TITLE
Add the I'm Interested Embedded form

### ISSUE THREAD

**Issue by elijahlofgren** [HackMGM/hackmgm.org#2]
- Name
- Email
- Interests/Skills
- Social media handles (twitter etc)
- Comments

**Comment by netelysis** [comment]
Looks as if the local news media has picked up on our little CfA 
efforts.  Please note the link below and the attached files from today's 
local paper.
- 
  http://www.montgomeryadvertiser.com/story/news/2016/08/30/hacking-montgomery-local-techies-get-national-backing/89581684/

## 

Boyd Stephens
Network Engineering Division

Netelysis, LLC
PO Box 230546
Montgomery, AL 36123

tel.    334.213.1128
web.    www.netelysis.com
email.  bstephens@netelysis.com

The information contained in this communication is confidential, may be subject to legal privileges, may constitute inside information, and is intended only for the use of the addressee. It is the property of Netelysis or its relevant affiliate. Unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful. If you have received this communication in error, please notify Netelysis immediately by return e-mail and destroy this communication and all copies thereof, including all attachments.
