### ISSUE TITLE
Create development branch

### ISSUE THREAD

**Issue by almostengr** [HackMGM/hackmgm.org#25]
Development branch needs to be created.  This will better align with Git workflows used in the IT industry. Also will allow for better release cycles.

**Comment by chukShirley** [comment]
This will depend on what kind of workflow we want. Lots of projects don't use develop branches. They just merge PRs to master and then tag new releases from master. See https://github.com/composer/composer as an example.

**Comment by almostengr** [comment]
This was something that was discussed in creating in a previous meeting as an enhancement for attempting to create the development workflow.

**Comment by chukShirley** [comment]
K. I was late to the party :)
`develop` branch has been created
https://github.com/HackMGM/hackmgm.org/tree/develop

What was the workflow that was decided on? Is it documented somewhere?

**Comment by almostengr** [comment]
No decisions were made.  It was agreed that ideas, comments, etc be posted on the discussion board on Meetup and on here as Issues.  Then at some point (perhaps future meeting) that those suggestions would be discussed among the members.

**Comment by elijahlofgren** [comment]
Here's my favorite workflow for Git: https://www.atlassian.com/git/tutorials/comparing-workflows#feature-branch-workflow

**Comment by almostengr** [comment]
Closing since Trello is being used.

**Comment by jacquelineIO** [comment]
@bitsecondal creating a development branch can't be replicated via Trello. I'm not sure I'm following this logic?

**Comment by almostengr** [comment]
@jacquelineflemming I typed the wrong thing.  I see that a development branch was created.
