### ISSUE TITLE
Mysterious Greater Than showing

### ISSUE THREAD

**Issue by almostengr** [HackMGM/hackmgm.org#26]
Greater than is showing up on the about.html and getinvolved.html pages. when viewed in the browser. This appears in both IE and Chrome browsers. Chrome shows it as being apart of the code. However when doing analysis, it does not show up in the HTML file.

![mysterious greater than](https://cloud.githubusercontent.com/assets/15150637/26738916/8a80bae2-4795-11e7-920d-4adeb036ba84.png)

![mysterious greater than ie](https://cloud.githubusercontent.com/assets/15150637/26738985/c1c407fc-4795-11e7-8bbf-96cfbc157797.png)

**Comment by bitsecondal** [comment]
This issue is also evident on the getinvolved.html page.

**Comment by chukShirley** [comment]
This was resolved in https://github.com/HackMGM/hackmgm.org/pull/17
Just need to deploy the changes
